### ISSUE TITLE
Needs documentation/help tags

### ISSUE THREAD

**Issue by evanrelf** [arithran/vim-pizza#1]
I should be able to type `:h OrderPizza` and get help using and configuring the plugin.

I believe this feature is critical to `vim-pizza`'s success in the global marketplace. Investors will be eager to fund `vim-pizza` once documentation can be viewed inside Vim itself.

**Comment by YodaEmbedding** [comment]
I remember when I first started using this plugin. Back when it was a small startup with big goals. Now we've got investors and shareholders to worry about. Managers and disgruntled employees to deal with. There were no fancy things like `:help` commands back in those days. We used `man` pages, like real men do.

How I miss those days.
